sonar.organization=anassarwar14
sonar.projectKey=Anassarwar14_anas-mern-10pshine
sonar.projectName=anas-mern-10pshine

sonar.sources=.
sonar.tests=tests

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx,tests/**/*.spec.ts,tests/**/*.spec.tsx

sonar.exclusions=**/node_modules/**, **/.next/**, **/out/**, **/coverage/**, **/dist/**, **/build/**, **/.husky/**, **/public/**, next.config.js, postcss.config.js, tailwind.config.js, **/*.config.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.typescript.file.suffixes=.ts,.tsx
sonar.javascript.file.suffixes=.js,.jsx

sonar.sourceEncoding=UTF-8